### ISSUE TITLE
База данных.

### ISSUE THREAD

**Issue by shindakioku** [sovetromantica/api#2]
Добавить [typeorm](http://typeorm.io/#/)
https://docs.nestjs.com/recipes/sql-typeorm

**Comment by mrcatlait** [comment]
@shindakioku Начал работу над этим таском и #6

**Comment by shindakioku** [comment]
@mrcatlait возьми только шестую.
У нас база лежит на удаленном сервере и я чуть позже добавлю миграции, чтобы можно было разрабатывать.

**Comment by shindakioku** [comment]
https://github.com/sovetromantica/api/tree/417b978b1e09f6849ad663437ffd788e1d26736e
